name: Build release from tag
on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tags
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

    - name: Install KO
      env:
        VERSION: "0.10.0"
      run: |
        curl -L https://github.com/google/ko/releases/download/v${VERSION}/ko_${VERSION}_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
    - name: Publish docker image
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
      run: |
        ./ko login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        ./ko publish -B --tags v${{ steps.version.outputs.tag }} .